server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/emeraldhieu/spring-cloud-config-playground.git
          searchPaths: config/{application}
          default-label: master
          clone-on-start: true
          username: emeraldhieu
          password: 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
  security:
    user:
      name: root
      password: s3cr3t
encrypt:
  keyStore:
    location: classpath:/keystore/config-server.jks
    password: haveaniceday
    alias: config-server-key
